on:
  issue_comment:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
  push:
    branches: [main, test-me-*]

jobs:
  main:
    if: "github.event.action != 'labeled' || github.event.label.name == 'pre-commit ci run'"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - run: gh pr edit ${{ github.event.number }} --remove-label 'pre-commit ci run'
      if: github.event.action == 'labeled' && github.event.label.name == 'pre-commit ci run'
      env:
        GH_TOKEN: ${{ github.token }}
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.1
    - uses: pre-commit-ci/lite-action@v1.1.0
      if: always()
