on:
  issue_comment:
  pull_request:
    types: [labeled, opened, reopened, synchronize]
  push:
    branches: [main, test-me-*]

jobs:
  main:
    if: "github.event.action != 'labeled' || github.event.label.name == 'pre-commit ci run'"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4
      with:
        python-version: 3.x
    - uses: pre-commit/action@v3.0.0
    - uses: pre-commit-ci/lite-action@allow-comments
      if: always()
